# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Homework' do
pod 'SDWebImage'
pod 'JRTActivityIndicator'
pod 'JRTAPIModel'
pod 'JRTStretchyHeaderTableView'
pod 'JRTNavigationBarStyle'
end

target 'HomeworkTests' do

end

target 'HomeworkUITests' do

end

