# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Homework' do
#pod 'JSONModel'
#pod 'AFNetworking'
pod 'SDWebImage'
pod 'JRTActivityIndicator'
pod 'JRTAPIModel'
end

target 'HomeworkTests' do

end

target 'HomeworkUITests' do

end

